version: "3.3"
   
services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
  
  web:
    build: ./backend
    entrypoint: ['/code/entrypoint.sh']
    env_file:
      - ./.env
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
