# Generated by Django 3.2.9 on 2021-11-30 05:49

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('in_progress', 'In progress'), ('reviewing', 'Reviewing'), ('finished', 'Finished')], max_length=30)),
                ('price', models.IntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOrderTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=100, populate_from='username', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.usertype'),
        ),
        migrations.CreateModel(
            name='StockOrderApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_models.stockorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockorder',
            name='applicant',
            field=models.ManyToManyField(blank=True, related_name='stock_applicant', through='db_models.StockOrderApplicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='db_models.StockOrderTags'),
        ),
        migrations.AlterUniqueTogether(
            name='stockorder',
            unique_together={('author', 'executor')},
        ),
    ]
