# Generated by Django 3.2.4 on 2021-07-05 19:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='admin-admin', editable=False, max_length=100, populate_from='username', unique=True),
            preserve_default=False,
        ),
    ]
