# Generated by Django 3.2.4 on 2021-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
