# Generated by Django 3.2.9 on 2021-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20211130_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='tags',
            field=models.ManyToManyField(to='db_models.StockOrderTags'),
        ),
    ]
