# Generated by Django 3.2.9 on 2021-11-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_alter_stockorder_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='tags',
            field=models.ManyToManyField(blank=True, to='db_models.StockOrderTags'),
        ),
    ]
