# Generated by Django 3.2.9 on 2021-11-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_auto_20210705_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.usertype'),
        ),
    ]
