# Generated by Django 3.2.4 on 2021-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_auto_20210705_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
