# Generated by Django 3.2.4 on 2021-07-23 07:15

import db_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_customuser_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=models.SET(db_models.models.get_or_create_user_type), to='db_models.usertype'),
        ),
    ]
