# Generated by Django 3.2.9 on 2021-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_alter_stockorder_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockOrderTags',
            new_name='StockOrderTag',
        ),
        migrations.RenameField(
            model_name='stockorder',
            old_name='applicant',
            new_name='applicants',
        ),
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
