# Generated by Django 3.2.9 on 2021-11-30 10:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_auto_20211130_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='first_order_blah_blah', editable=False, max_length=150, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
