# Generated by Django 3.2.9 on 2022-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
