# Generated by Django 3.2.9 on 2022-01-14 22:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0003_auto_20220113_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapplicant',
            name='image',
        ),
        migrations.AddField(
            model_name='orderapplicant',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='media', to='app_utils.MediaStorage'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='username', unique=True),
        ),
    ]
