# Generated by Django 3.2.9 on 2022-01-16 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0004_auto_20220115_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='app_utils.OrderApplicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderapplicant',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='media', to='app_utils.MediaStorage'),
        ),
    ]
