# Generated by Django 3.2.9 on 2022-01-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utils', '0005_auto_20220116_1325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderapplicant',
            unique_together={('applicant', 'order')},
        ),
    ]
